version: '3.8'

services:
  countryincek-app:
    build: .
    container_name: countryincek
    ports:
      - "3000:80" # Cloudflare panelinde 5000 portunu tanımladıysanız bu şekilde kalsın; 3000 tanımladıysanız "3000:80" yapın
    restart: always